/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.vistas;

import edu.cecar.controladores.ControladorCliente;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Vincenzo Angelone
 */
public final class VistaLogPanel extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogPanel
     */
    static boolean conectado;

    static ControladorCliente controladorCliente = new ControladorCliente();

    public VistaLogPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
        panel_registro.setVisible(false);
        String path = System.getProperty("user.dir");
        Image icon = Toolkit.getDefaultToolkit().getImage(path + "\\src\\main\\resources\\icono_gorest.png");
        this.setIconImage(icon);
        if (conectado == false) {
            if (controladorCliente.conectarClienteServidor("127.0.0.1", 17000) == false) {
                JOptionPane.showMessageDialog(null, "No hay conexion con el servidor, intente nuevamente.");
                System.exit(0);
            }
            conectado = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_entrar = new javax.swing.JPanel();
        bt_Entrar = new javax.swing.JButton();
        pass_Contraseña = new javax.swing.JPasswordField();
        text_Usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_registrarse = new javax.swing.JButton();
        panel_registro = new javax.swing.JPanel();
        bt_registro = new javax.swing.JButton();
        pass_ContraseñaRegistro = new javax.swing.JPasswordField();
        text_UsuarioRegistro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt_Logearse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GoRest");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(615, 450));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setForeground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 30);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_gorest.PNG"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(240, 0, 140, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 30, 610, 60);

        panel_entrar.setBackground(new java.awt.Color(255, 204, 102));

        bt_Entrar.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        bt_Entrar.setText("Iniciar Sesión");
        bt_Entrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EntrarActionPerformed(evt);
            }
        });

        pass_Contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_ContraseñaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass_ContraseñaKeyTyped(evt);
            }
        });

        text_Usuario.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        text_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_UsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_UsuarioKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel3.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setText("Contraseña: ");

        bt_registrarse.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        bt_registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_person_add_black_18dp.png"))); // NOI18N
        bt_registrarse.setText("Registrar");
        bt_registrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_entrarLayout = new javax.swing.GroupLayout(panel_entrar);
        panel_entrar.setLayout(panel_entrarLayout);
        panel_entrarLayout.setHorizontalGroup(
            panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_entrarLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_entrarLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_entrarLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_entrarLayout.createSequentialGroup()
                        .addComponent(bt_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        panel_entrarLayout.setVerticalGroup(
            panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_entrarLayout.createSequentialGroup()
                .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_entrarLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_entrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_Contraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        getContentPane().add(panel_entrar);
        panel_entrar.setBounds(0, 90, 610, 360);

        panel_registro.setBackground(new java.awt.Color(255, 204, 102));

        bt_registro.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        bt_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_person_add_black_18dp.png"))); // NOI18N
        bt_registro.setText("Registrarse");
        bt_registro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registroActionPerformed(evt);
            }
        });

        pass_ContraseñaRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_ContraseñaRegistroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass_ContraseñaRegistroKeyTyped(evt);
            }
        });

        text_UsuarioRegistro.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        text_UsuarioRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_UsuarioRegistroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_UsuarioRegistroKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel4.setText("Usuario:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setText("Contraseña: ");

        bt_Logearse.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        bt_Logearse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_home_black_18dp.png"))); // NOI18N
        bt_Logearse.setText("Inicio");
        bt_Logearse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_Logearse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LogearseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_registroLayout = new javax.swing.GroupLayout(panel_registro);
        panel_registro.setLayout(panel_registroLayout);
        panel_registroLayout.setHorizontalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_UsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(bt_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Logearse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass_ContraseñaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        panel_registroLayout.setVerticalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_UsuarioRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_ContraseñaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Logearse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        getContentPane().add(panel_registro);
        panel_registro.setBounds(0, 90, 610, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EntrarActionPerformed
        try {
            boolean flag = false;
            String path = System.getProperty("user.dir");
            File archivo_credenciales = new File(path + "\\Archivos\\archivo_credenciales.txt");
            String contenido;
            try (PrintWriter pw = new PrintWriter(archivo_credenciales)) {
                pw.println(text_Usuario.getText());
                pw.println(pass_Contraseña.getText());
            }
            controladorCliente.PeticionCliente("login");
            File respuesta_login = new File(path + "\\Archivos\\respuesta_login.txt");
            try (FileReader lector = new FileReader(respuesta_login)) {
                BufferedReader bf = new BufferedReader(lector);
                while ((contenido = bf.readLine()) != null) {
                    if (contenido.equals("true")) {
                        flag = true;
                        break;
                    }
                }
                if (flag == true) {
                    bf.close();
                    lector.close();
                    dispose();
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new VistaPrincipal().setVisible(true);
                        }
                    });
                } else {
                    JOptionPane.showMessageDialog(null, "Credenciales incorrectas.");
                }
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
        }

    }//GEN-LAST:event_bt_EntrarActionPerformed

    private void pass_ContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_ContraseñaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                boolean flag = false;
                String path = System.getProperty("user.dir");
                File archivo_credenciales = new File(path + "\\Archivos\\archivo_credenciales.txt");
                String contenido;
                try (PrintWriter pw = new PrintWriter(archivo_credenciales)) {
                    pw.println(text_Usuario.getText());
                    pw.println(pass_Contraseña.getText());
                }
                controladorCliente.PeticionCliente("login");
                File respuesta_login = new File(path + "\\Archivos\\respuesta_login.txt");
                FileReader lector = new FileReader(respuesta_login);
                BufferedReader bf = new BufferedReader(lector);
                while ((contenido = bf.readLine()) != null) {
                    if (contenido.equals("true")) {
                        flag = true;
                        break;
                    }
                }
                if (flag == true) {
                    bf.close();
                    lector.close();
                    dispose();
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new VistaPrincipal().setVisible(true);
                        }
                    });
                } else {
                    JOptionPane.showMessageDialog(null, "Credenciales incorrectas.");
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
            }
        }

    }//GEN-LAST:event_pass_ContraseñaKeyPressed

    private void bt_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registroActionPerformed
        // TODO add your handling code here:
        try {
            boolean flag = false;
            String path = System.getProperty("user.dir");
            File archivo_registro = new File(path + "\\Archivos\\archivo_registro.txt");
            String contenido;
            try (PrintWriter pw = new PrintWriter(archivo_registro)) {
                pw.println(text_UsuarioRegistro.getText());
                pw.println(pass_ContraseñaRegistro.getText());
            }
            controladorCliente.PeticionCliente("registro");
            File respuesta_registro = new File(path + "\\Archivos\\respuesta_registro.txt");
            try (FileReader lector = new FileReader(respuesta_registro)) {
                BufferedReader bf = new BufferedReader(lector);
                while ((contenido = bf.readLine()) != null) {
                    if (contenido.equals("true")) {
                        flag = true;
                        break;
                    }
                }
                if (flag == true) {
                    JOptionPane.showMessageDialog(null, "Registro completado.");
                    panel_registro.setVisible(false);
                    panel_entrar.setVisible(true);
                } else {
                    archivo_registro.delete();
                    respuesta_registro.delete();
                    JOptionPane.showMessageDialog(null, "Error datos erroneos o faltantes.");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
        }
    }//GEN-LAST:event_bt_registroActionPerformed

    private void pass_ContraseñaRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_ContraseñaRegistroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                boolean flag = false;
                String path = System.getProperty("user.dir");
                File archivo_registro = new File(path + "\\Archivos\\archivo_registro.txt");
                PrintWriter pw = new PrintWriter(archivo_registro);
                String contenido;
                pw.println(text_UsuarioRegistro.getText());
                pw.println(pass_ContraseñaRegistro.getText());
                pw.close();
                controladorCliente.PeticionCliente("registro");
                File respuesta_registro = new File(path + "\\Archivos\\respuesta_registro.txt");
                FileReader lector = new FileReader(respuesta_registro);
                BufferedReader bf = new BufferedReader(lector);
                while ((contenido = bf.readLine()) != null) {
                    if (contenido.equals("true")) {
                        flag = true;
                        break;
                    }
                }
                if (flag == true) {
                    JOptionPane.showMessageDialog(null, "Registro completado.");
                    panel_registro.setVisible(false);
                    panel_entrar.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Error datos erroneos o faltantes.");
                }
                lector.close();
            } catch (Exception ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "No hay conexion con la base de datos, intente nuevamente.");
            }
        }
    }//GEN-LAST:event_pass_ContraseñaRegistroKeyPressed

    private void bt_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarseActionPerformed
        // TODO add your handling code here:
        text_Usuario.setText("");
        text_UsuarioRegistro.setText("");
        pass_Contraseña.setText("");
        pass_ContraseñaRegistro.setText("");
        panel_entrar.setVisible(false);
        panel_registro.setVisible(true);
    }//GEN-LAST:event_bt_registrarseActionPerformed

    private void bt_LogearseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LogearseActionPerformed
        // TODO add your handling code here:
        text_Usuario.setText("");
        text_UsuarioRegistro.setText("");
        pass_Contraseña.setText("");
        pass_ContraseñaRegistro.setText("");
        panel_entrar.setVisible(true);
        panel_registro.setVisible(false);
    }//GEN-LAST:event_bt_LogearseActionPerformed

    private void text_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_UsuarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_UsuarioKeyPressed

    private void text_UsuarioRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_UsuarioRegistroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_UsuarioRegistroKeyPressed

    private void text_UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_UsuarioKeyTyped
        // TODO add your handling code here
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_text_UsuarioKeyTyped

    private void pass_ContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_ContraseñaKeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_pass_ContraseñaKeyTyped

    private void text_UsuarioRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_UsuarioRegistroKeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_text_UsuarioRegistroKeyTyped

    private void pass_ContraseñaRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_ContraseñaRegistroKeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_pass_ContraseñaRegistroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Entrar;
    private javax.swing.JButton bt_Logearse;
    private javax.swing.JButton bt_registrarse;
    private javax.swing.JButton bt_registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_entrar;
    private javax.swing.JPanel panel_registro;
    private javax.swing.JPasswordField pass_Contraseña;
    private javax.swing.JPasswordField pass_ContraseñaRegistro;
    private javax.swing.JTextField text_Usuario;
    private javax.swing.JTextField text_UsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
